### ISSUE TITLE
Add the function `branching_logic`

### ISSUE THREAD

**Issue by danielebottigliengo** [UBESP-DCTV/csm#12]
Aggiungere la funzione `create_branching_logic`. Lo scopo della funzione è quello di associare a ciascuna variabile della base di dati importata da Redcap il relativo branching logic (se presente), in modo da identificare i dati mancanti reali da quelli strutturali (ovvero quelli mancanti per via del branching logic).

**Comment by CorradoLanera** [comment]
Se lo scopo è associare, perché si chiama “crea...”? Inoltre, non è che magari a questo punto ti conviene creare proprio una struttura dati ad hoc? Non so... pensiamoci

**Comment by danielebottigliengo** [comment]
Modificato. La funzione servirà per creare il branching logic da associare a ogni tabella creata dalla funzione `nest_tables` (#16) e inserirlo poi nella classe `redcap_csm` (#17).
