### ISSUE TITLE
Problems with codecov

### ISSUE THREAD

**Issue by danielebottigliengo** [UBESP-DCTV/csm#14]
Alcuni checks non sono passati relativi al codecov in #11. Per caso è qualcosa relativo allo stile di programmazione?

**Comment by CorradoLanera** [comment]
Non è un bug :-)
Codecov di dice la copertura di test che hai fatto, in porzione al codice che hai scritto. L'errore lo da perchè per sicurezza e qualità ci sono delle soglie (per capire quali sono: https://docs.codecov.io/docs/codecov-delta) impostate, che questo push ha superato (per vedere le soglie di default: https://codecov.io/gh/UBESP-DCTV/csm/settings/yaml). In particolare (che scrive lo stesso errore), a livello globale di progetto la porzione di codice testato è scesa dell 11.12% che è più dell'1% concesso... ho hai tolto troppi test, o hai aggiunto troppe funzionalità non testate. 

Ovviamente sei admin, quindi se lo hai fatto a ragione e "vuoi" che sia così allora fai il merge comunque, altrimenti implementa test, sensati, a sufficienza per arrivare alla copertura necessaria.

Richiamando dalla cartella del pacchetto in RStudio la funzione

```
covr::report()
```

hai il report del progetto cosi puoi vedere cosa è stato e non `1e stato testato e vedere che righe di codice hai scritto ma non hai testato.

**Comment by danielebottigliengo** [comment]
Ok, grazie. Devo ancora capire come dare le labels! :-)

Comunque la questione era proprio relativa ai test: c'era una porzione di corpo della funzione non testata. `covr::report` è stato molto utile. Thanks @CorradoLanera !
