### ISSUE TITLE
Create the class `redcap_csm`

### ISSUE THREAD

**Issue by danielebottigliengo** [UBESP-DCTV/csm#17]
Creare la classe `redcap_csm`. La classe sarà una tibble che conterrà le seguenti colonne:

- fields
- sheets
- tables
- branching_logic

**Comment by CorradoLanera** [comment]
Una classe è una struttura dati con allegati relativi metadati. Non so cosa significhino le cose che hai scritto (lo sai tu) , attenzione solo che una tibble è una "tabella" in cui si suppone che ogni riga sia una osservazione, ogni colonna una caratteristica. Se metti insieme più "tipi" di dati, forse meglio appoggiarsi a una lista come struttura base (di cui magari ogni elemento è una tibble) e poi mettere come attributi i metadatai che riguardano tutto l'insieme generale della struttura (l'intera lista). Fammi sapere :-)

**Comment by danielebottigliengo** [comment]
Ok, grazie mille del consiglio. Ora valuto bene come impostare la classe. Effettivamente una lista asrebbe più comoda da gestire in questo senso.

**Comment by CorradoLanera** [comment]
O magari anche più di una classe! Perchè no?

**Comment by danielebottigliengo** [comment]
Cosa intendi con anche più di una classe?

**Comment by CorradoLanera** [comment]
che se hai 4 tipi di oggetti e vuoi metterli in una lista... se sono "una cosa sola" puoi tenerli così e fare la tua classe...ma magari potrebbe avere senso fare 4 classi, o forse no, non so... era solo un opzione da tenere a mente, non è che sei corstretto a fare solo "una" classe

**Comment by danielebottigliengo** [comment]
Ok, grazie. Terrò a mente anche questo aspetto.
