### ISSUE TITLE
Make read_redcap tests faster

### ISSUE THREAD

**Issue by CorradoLanera** [UBESP-DCTV/csm#8]
Ci stanno circa 20 secondi...è tantissimo. Credo il problema sia solo che la connessione al db è fatta per ogni test. Visto che quella connessione è pubblica e gestita dagli sviluppatori di `{REDCapR}`, la richiametrei una sola volta (certo che funzioni), fuori dai test, e poi testerei l'effetto con le funzioni `{csm}`.

**Comment by danielebottigliengo** [comment]
Risolto secondo i tuoi suggerimenti.
