### ISSUE TITLE
Add warning for user (under active development)

### ISSUE THREAD

**Issue by CorradoLanera** [UBESP-DCTV/csm#9]
Secondo me sarebbe comunque da avvisare (nel `README`) che per il momento nessuna funzione è da considerarsi stabile (e infatti non è sul CRAN nemmeno per sogno), e quindi di usarle e sperimentarle wpiù che volentieri se qualcuno vuole, ma considerare che le interfacce (nomi, tipi, ordine, ... delle funzioni e degli argomenti che richiedono) non sono assolutamente stabili per ora e non c'è alcuna garanzia che lo rimangano

**Comment by danielebottigliengo** [comment]
Inserito il warning.
